### ISSUE TITLE
Rename to be organism-neutral or continue on with cats?

### ISSUE THREAD

**Issue by RavingRavenpaw** [ChromeFusion44/Cat-Genetics#6]
Currently deciding if I should eliminate the cat references and naming conventions in the program because the features regarding cats never got implemented, or keep them and implement the cat features.

I'll make up my mind eventually.

Also, if I go with cat stuff, I'll be doing some re-reading and research into cat genetics once more.
## To choose:
- [x] Go organism-neutral
- [ ] Stick with cat naming conventions and implement previously planned cat features

**Comment by RavingRavenpaw** [comment]
Going to be going organism neutral.
Renamed the project as well.

Check out [bb51403](https://github.com/RavingRavenpaw/punnet-squared/commit/bb51403a39ae9775128672f2518e4e88ee55508e).

**Comment by ghost** [comment]
Aww. I kinda wanted it to be with cats. BTW this is really awesome, could you provide examples of how to format and type the genotypes in?

**Comment by RavingRavenpaw** [comment]
Aww, thanks! I'll actually add a wiki page on how to use the program now, but basically, do this:
1. Execute "punnet squared.py" in your IDE or with the python interpreter
2. Enter the first organism's genotype (it only supports two alleles atm, so do something like Bb or GG) and hit enter
3. Do the same for the second organism's genotype and hit enter
4. Voila! Results!
5. Press any key to close the program.

I think I might add all the cat features back in at some point, but I want to finish everything up first - I'm kinda putting them as a secondary goal for this little project. :0

**Comment by ghost** [comment]
Ok thx.
